export const installed_blueprints = [
  //@BlueprintInsertion
{ name: 'Messaging7789', human_name: 'Messaging', access_route: 'Messaging7789', icon: 'comments'},
{ name: 'EmailAuth7788', human_name: 'Email Auth', access_route: 'EmailAuth7788', icon: 'envelope-o'},
{ name: 'CalendarView7787', human_name: 'Calendar View', access_route: 'CalendarView7787', icon: 'calendar'},
{ name: 'Messaging7784', human_name: 'Messaging', access_route: 'Messaging7784', icon: 'comments'},
{ name: 'EmailAuth7783', human_name: 'Email Auth', access_route: 'EmailAuth7783', icon: 'envelope-o'},
{ name: 'CalendarView7782', human_name: 'Calendar View', access_route: 'CalendarView7782', icon: 'calendar'},
{ name: 'UserProfile47781', human_name: 'User Profile 4', access_route: 'UserProfile47781'},
{ name: 'BlankScreen57780', human_name: 'Blank Screen 5', access_route: 'BlankScreen57780'},
{ name: 'EmailAuth17570', human_name: 'Email Auth 1', access_route: 'EmailAuth17570', icon: 'envelope-o'},
{ name: 'EmailAuth27569', human_name: 'Email Auth 2', access_route: 'EmailAuth27569', icon: 'envelope-o'},
{ name: 'EmailAuth37568', human_name: 'Email Auth 3', access_route: 'EmailAuth37568', icon: 'envelope-o'},
{ name: 'EmailAuth17567', human_name: 'Email Auth 1', access_route: 'EmailAuth17567', icon: 'envelope-o'},
{ name: 'EmailAuth27566', human_name: 'Email Auth 2', access_route: 'EmailAuth27566', icon: 'envelope-o'},
{ name: 'EmailAuth37565', human_name: 'Email Auth 3', access_route: 'EmailAuth37565', icon: 'envelope-o'},
{ name: 'EmailAuth17560', human_name: 'Email Auth 1', access_route: 'EmailAuth17560', icon: 'envelope-o'},
{ name: 'EmailAuth27559', human_name: 'Email Auth 2', access_route: 'EmailAuth27559', icon: 'envelope-o'},
{ name: 'EmailAuth37557', human_name: 'Email Auth 3', access_route: 'EmailAuth37557', icon: 'envelope-o'},
{ name: 'Messaging7556', human_name: 'Messaging', access_route: 'Messaging7556', icon: 'comments'},
{ name: 'EmailAuth7555', human_name: 'Email Auth', access_route: 'EmailAuth7555', icon: 'envelope-o'},
{ name: 'CalendarView7554', human_name: 'Calendar View', access_route: 'CalendarView7554', icon: 'calendar'},
{ name: 'BlankScreen57552', human_name: 'Blank Screen 5', access_route: 'BlankScreen57552'},
{ name: 'BlankScreen67551', human_name: 'Blank Screen 6', access_route: 'BlankScreen67551'},
{ name: 'Messaging37550', human_name: 'Messaging 3', access_route: 'Messaging37550', icon: 'comments'},
{ name: 'CalendarView47549', human_name: 'Calendar View 4', access_route: 'CalendarView47549', icon: 'calendar'},
{ name: 'UserProfile47548', human_name: 'User Profile 4', access_route: 'UserProfile47548'},
{ name: 'UserProfile57545', human_name: 'User Profile 5', access_route: 'UserProfile57545'},
{ name: 'BlankScreen67544', human_name: 'Blank Screen 6', access_route: 'BlankScreen67544'},
{ name: 'BlankScreen47541', human_name: 'Blank Screen 4', access_route: 'BlankScreen47541'},
{ name: 'Messenger', human_name: 'Messenger', access_route: 'Messenger', icon: 'comments'},
{ name: 'Calendar', human_name: 'Calendar', access_route: 'Calendar', icon: 'calendar'},
{ name: 'EmailAuth', human_name: 'EmailAuth', access_route: 'EmailAuth', icon: 'envelope-o'},

  // you can add more installed blueprints here
  // access route is the route nate given to navigator
];
