# Generated by Django 2.2.14 on 2020-07-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200702_0814"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fggrfgfgfgfg",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="fhhfhhhhh",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
