# Generated by Django 2.2.14 on 2020-07-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200702_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fggrfgfgfgfg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fhhfhhhhh',
        ),
    ]
